import type { Metadata } from 'next';
import { Orbit } from 'next/font/google';
import './globals.css';

const orbit = Orbit({ subsets: ['latin'], weight: '400' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={orbit.className}>{children}</body>
    </html>
  );
}
